config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  devise_for :users
  root to: 'homes#top'
  get 'about' => 'homes#about'
  resources :items do
    resource :favorites, only: [:create, :destroy]

    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
  end
  get 'search' => "searches#search"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  attachment :image
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :tags, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true

  # フォロー機能
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # 検索機能
  def self.looks(searches, words)
    if searches == "perfect_match"
      @item = Item.where("title LIKE ?", "#{words}")
    else
      @item = Item.where("title LIKE ?", "%#{words}%")
    end
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

# フォロー機能
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end

  # 検索機能
  def self.looks(searches, words)
    if searches == "perfect_match"
      @user = User.where("name LIKE ?", "#{words}")
    else
      @user = User.where("name LIKE ?", "%#{words}%")
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    items_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    item = Item.find(params[:item_id])
    comment = current_user.comments.new(comment_params)
    comment.item_id = item.id
    comment.save
    redirect_to item_path(item)
  end

  def destroy
    Comment.find_by(id: params[:id]).destroy
    redirect_to item_path(params[:item_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    item = Item.find(params[:item_id])
    favorite = current_user.favorites.new(item_id: item.id)
    favorite.save
    redirect_to item_path(item)
  end

  def destroy
    item = Item.find(params[:item_id])
    favorite = current_user.favorites.find_by(item_id: item.id)
    favorite.destroy
    redirect_to item_path(item)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    if @item.save
      tags = Vision.get_image_data(@item.image)    
      tags.each do |tag|
        @item.tags.create(name: tag)
    end
      redirect_to items_path
    else
      render :new
    end
  end

  def index
    @items = Item.page(params[:page]).reverse_order
  end

  def show
    @item = Item.find(params[:id])
    @comment = Comment.new
    @user = @item.user
  end

  def edit
    @item = Item.find(params[:id])
    @user = @item.user
    if @user.id == current_user.id

    else
    redirect_to items_path
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
    flash[:notice]= 'You have updated book successfully.'
    redirect_to item_path(@item.id)
    else
    render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end

   private

  def item_params
    params.require(:item).permit(:title, :image, :body)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  # フォロー機能を作成・保存・削除する
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  # フォロー・フォロワー一覧を表示する
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @range = params[:range]
    @word = params[:word]

    if @range == "ユーザー"
      @users = User.looks(params[:search], params[:word])
    else
      @items = Item.looks(params[:search], params[:word])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
    @items = @user.items.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        UserMailer.with(user: @user).welcome_email.deliver_later

        format.html { redirect_to(@user, notice: 'ユーザーが正常に作成されました。') }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_list.html.erb
<% if user_signed_in? %>
<div class="col-lg-3">
<h2>User info</h2>
<table class="table">
  <tbody>
    <tr>
      <%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", format: 'jpeg', size: "100x100" %>
    </tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>follows</th>
      <th><%= link_to (user.followings.count), user_followings_path(user) %></th>
    </tr>
    <tr>
      <th>followers</th>
      <th><%= link_to (user.followers.count), user_followers_path(user) %></th>
    </tr>
    <th><% if user.id != current_user.id %>
      <% if current_user.following?(user) %>
      <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class: "btn btn-sm btn-info" %>
      <% else %>
      <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-sm btn-success" %>
      <% end %>
      <% end %>
    </th>
    </tbody>
  </table>
  <div class="row">
    <% if user_signed_in? %>
    <% if user.id == current_user.id %>
    <%= link_to 'マイページ', edit_user_path(user),class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" %>
    <% end %>
    <% end %>
  </div>
  </div>
  <% else %>
  <div class="col-lg-3">
    <h2>User info</h2>
    <p><%= link_to 'ログイン', new_user_session_path, class: "btn btn-sm btn-success btn-block" %></p><br>
    <p><%= link_to '新規登録', new_user_registration_path, class: "btn btn-sm btn-info btn-block" %></p>
  </div>
  <% end %>

app/views/items/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		  <h1>投稿編集</h1>
  		  <% if @item.errors.any? %>
          <% @item.errors.full_messages.each do |message| %>
          <%= message %>error
          <% end %>
        <% end %>
        <%= form_with model: @item, local:true do |f| %>
          <div>
            <label>Title</label>
            <p><%= f.text_field :title %></p>
          </div>
          <div>
            <label>Opinion</label>
            <p><%= f.text_area :body %></p>
          </div>
          <div>
            <%= f.submit 'Update Book' %>
          </div>
    		<% end %>
        <%= link_to "Show", item_path(@item.id) %>

        |

        <%= link_to "Back", items_path %>
      </div>
    </div>
  </div>
</main>

app/views/items/index.html.erb
<div class="container">
  <div class="row">
    <%= render 'items/list', user: current_user,item: @item  %>


    <div class="col-md-8 offset-md-1">
      <h2>投稿一覧</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td><%= link_to (attachment_image_tag item.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size: "40x40"), user_path(item.user_id) %></td>
              <td><%= link_to (item.title), item_path(item.id) %></td>
              <td><%= item.body %></td>
              <td>
                <% if user_signed_in? %>
                <% if item.user.id != current_user.id %>
                <% if item.favorited_by?(current_user) %>
              <p>
                <%= link_to item_favorites_path(item), method: :delete, class: "like" do %>
                  ♥<%= item.favorites.count %>
                <% end %>
              </p>
              <% else %>
              <p>
                <%= link_to item_favorites_path(item), method: :post do %>
                  ♥<%= item.favorites.count %>
                <% end %>
              </p>
            <% end %>
            <% end %>
              </td>
              <td>コメント数：<%= item.comments.count %></td>
            </tr>
          <% end %>
         <% end %>
        </tbody>
      </table>
      </div>
    </div>
  </div>
</div>
<%= paginate @items %>

app/views/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-2">
<h1>投稿フォーム</h1>
<% if @item.errors.any? %>
  <%= @item.errors.count %>件のエラーが発生しました
  <% @item.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<%= form_with model: @item, local:true do |f| %>
  <h4>画像</h4>
  <%= f.attachment_field :image %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  <h4>説明</h4>
  <%= f.text_area :body %>
  <%= f.submit '投稿' %>
<% end %>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="container">
  <div class="row">
<%= render 'items/list', user: @user,item: @item  %>
<div class="col-md-8 offset-md-1">
  <h2>投稿詳細</h2>
<div>
  <%= attachment_image_tag @item, :image, :fill, 300,200, fallback: "no_image.jpg" %>
  <div><% @item.tags.each do |tag| %>
    <span class="label"><%= tag.name %></span>
  <% end %>
  </div>
  <p>タイトル：<%= @item.title %></p>
  <p>説明：<%= @item.body %></p>
  <p>ユーザーネーム：<%= @item.user.name %></p>
  <p>投稿日時：<%= @item.created_at.strftime('%Y/%m/%d') %></p>
  <% if user_signed_in? %>
  <% if @item.user == current_user %>
    <%= link_to "削除", item_path(@item), method: :delete %>
    <%= link_to "編集", edit_item_path(@item) %>
  <% end %>
  <% if @user.id != current_user.id %>
  <% if @item.favorited_by?(current_user) %>
    <p>
      <%= link_to item_favorites_path(@item), method: :delete do %>
        ♥<%= @item.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to item_favorites_path(@item), method: :post do %>
        ♡<%= @item.favorites.count %> いいね
      <% end %>
    </p>
    <% end %>
  <% end %>
  <% end %>
</div>

<div>
<p>コメント件数：<%= @item.comments.count %></p>
<% @item.comments.each do |comment| %>
  <p><%= attachment_image_tag comment.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></p>
  <%= comment.user.name %>
  <%= comment.created_at.strftime('%Y/%m/%d') %><%= comment.comment %>
  <% if comment.user == current_user %>
  <div>
    <%= link_to "削除", item_comment_path(comment.item, comment), method: :delete %>
  </div>
  <% end %>
<% end %>
</div>
<% if user_signed_in? %>
<div>
<%= form_with(model:[@item, @comment], local: true) do |f| %>
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
  <%= f.submit "送信する" %>
<% end %>
</div>
<% end %>
</div>
    </div>
    </div>

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
  <thead>
    <tr>
      <th>name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
  <thead>
    <tr>
      <th>name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 px-5 mx-auto">
      <h2>プロフィール編集</h2>
      <%= form_with model:@user, local:true do |f| %>
        <label for="inputName">Name</label>
        <p><%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%></p>
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
        <label for="inputImage">ProfileImage</label>
        <p><%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %></p>
        <%= f.submit "変更を保存" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
<%= render 'items/list', user: current_user %>

<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
  <table class="table">
  <thead>
  <tr>
  <th>image</th>
  <th>name</th>
  <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
  <tr>
    <td><%= link_to (attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size: "40x40"), user_path(user.id) %></td>
    <td><%= user.name %></td>
    <td>フォロー数: <%= user.followings.count %></td>
    <td>フォロワー数: <%= user.followers.count %></td>

    <% if user_signed_in? %>
    <td>
    <% if user.id != current_user.id %>
    <% if current_user.following?(user) %>
    <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete %>
    <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
    <% end %>
    <% end %>
    </td>
    <% end %>
    <td><%= link_to "Show", user_path(user.id) %></td>
  </tr>
 <% end %>

  </tbody>
  </table>
</div>
</div>
</div>
    </div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
<%= render 'items/list', user: @user, item: @item  %>

<div class="col-md-8 offset-md-1">
  <h2>投稿</h2>
  <table class="table">
  <thead>
  <tr>
  <th></th>
  <th>Title</th>
  <th>Opinion</th>
  <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
  <tr>
    <td>
      <%= link_to user_path(@user) do %>
      <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size: "40x40" %><br>
      <% end %>
      </td>
    <td><%= link_to item.title, item_path(item.id) %></td>
    <td><%= item.body %></td>
  </tr>
  <% end %>

  </tbody>
  </table>
</div>
</div>
</div>
    </div>
<%= paginate @items %>